/// Auto-generated by scripts/apply_brand.ps1
/// Do not edit manually.
class BrandConfig {
  static const String packageName = 'kr.co.grib.claix';
  static const String updateRequestPackageName = 'MAIN_CLAIX_WIN';
}