/// Auto-generated by scripts/apply_brand.ps1
/// Do not edit manually.
class BrandTexts {
  static const String bottomBarMonitoring = '수업현황';
  static const String bottomBarGroupLesson = '모둠수업';
  static const String bottomBarScreenShare = '화면공유';
  static const String bottomBarFocusMode = '집중모드';
  static const String bottomBarChat = '클톡';
  static const String bottomBarSettings = '설정';
  static const String bottomBarEndClass = '수업종료';

  static const String lessonNormal = '일반수업';
  static const String lessonGroup = '모둠수업';
  static const String lessonNormalProgress = '일반수업 진행 중';
  static const String lessonGroupProgress = '모둠수업 진행 중';
}