import 'package:flutter/material.dart';

/// Auto-generated by scripts/apply_brand.ps1
/// Do not edit manually.
class BrandColors {
  static const Color primaryGradientStart = Color(0xFF0BA9FE);
  static const Color primaryGradientEnd = Color(0xFF457DFF);
  static const Color primaryButtonText = Color(0xFFFFFFFF);
  static const Color cardShadow = Color(0xFF70ABFF);

  static const Color selectTileBorderSelected = Color(0xFF457DFF);
  static const Color selectTileBorderDefault = Color(0xFFE5E5E5);
  static const Color selectTileShadow = Color(0xFF769DDF);

  static const Color selectPromptBackground = Color(0xFFF2F3F5);
  static const Color selectPromptText = Color(0xFF6D7882);

  static const Color inputFillBackground = Color(0xFFF3F4F6);
  static const Color loginInputFocusedBorder = Color(0xFF3A8BF9);
  static const Color labelText = Color(0xFF1E2124);

  static const Color bottomBarActive = Color(0xFF006CFF);
  static const Color bottomBarInactive = Color(0xFF464C53);
  static const Color bottomBarDanger = Color(0xFFBD2C0F);
  static const Color bottomBarGroupEnabledBackground = Color(0xFFD9EBFF);
  static const Color bottomBarFuncGradientStart = Color(0xFF0E9FFF);
  static const Color bottomBarFuncGradientEnd = Color(0xFF0977FF);

  static const double loginBgOpacity = 0.4;

  static const Color groupLessonTopButtonPrimary = Color(0xFF0B7BFF);
  static const Color groupLessonTopButtonDanger = Color(0xFFF05F42);
  static const Color groupLessonTopButtonOutlineBackground = Color(0xFFECF2FE);
  static const Color groupLessonTopButtonOutlineBorder = Color(0xFF3A8BF9);
  static const Color groupLessonTopButtonOutlineText = Color(0xFF002A63);
  static const Color groupLessonArrangeTitleText = Color(0xFF2E3440);
  static const Color groupLessonArrangeTitleBackground = Color(0xFFF3F5F7);
  static const Color groupLessonRenameButtonBackground = Color(0xFF0B7BFF);

  static const Color sidePanelTitleBackground = Color(0xFFD2DFF9);

  static const Color settingsButtonPrimary = Color(0xFF0F6FFF);
  static const Color settingsButtonText = Color(0xFF083891);
  static const Color settingsButtonBackground = Color(0xFFE9F2FF);
  static const Color settingsNameOuterGradientStart = Color(0xFFCAD9F7);
  static const Color settingsNameOuterGradientEnd = Color(0xFFA4C4E0);

  static const double settingsRoleImageHeight = 130;
  static const double settingsFileSelectButtonRadius = 6;
  static const double chatFileSelectButtonRadius = 28;
  static const double chatInputBorderRadius = 30;
  static const Color chatFileButtonBackground = Color(0xFFFFFFFF);
  static const Color chatFileButtonIcon = Color(0xFF2F6BFF);
  static const Color chatSendButtonBackground = Color(0xFFFFFFFF);
  static const Color chatSendButtonIconEnabled = Color(0xFF2F6BFF);
  static const Color chatSendButtonIconDisabled = Color(0xFFB9C7E7);
  static const bool chatShowAvatar = true;
  static const Color chatBubbleSentBackground = Color(0xFFEAF1FF);
  static const Color chatBubbleReceivedBackground = Color(0xFFFFFFFF);
  static const Color chatBubbleSentTimeText = Color(0xFF4A6FAF);
  static const Color chatBubbleReceivedTimeText = Color(0xFF7A879A);
  static const bool chatComposerBottomGradient = true;
  static const double loginBgCharacterHeight = 609;
  static const bool bottomBarShowLeftLogo = true;
  static const double quickCommandBarRadius = 28;
  static const double quickCommandBarButtonRadius = 28;
  static const Color quickCommandBarButtonSelectedBackground = Color(0xFF9DCCED);
  static const Color quickCommandBarButtonSelectedText = Color(0xFF142632);
  static const Color quickCommandBarButtonUnselectedText = Color(0xFF6D7882);
  static const Color quickCommandBarButtonIconSelected = Color(0xFF1F4F8A);
  static const Color quickCommandBarButtonIconUnselected = Color(0xFF7A8796);
  static const Color quickCommandBarButtonSelectedInnerBackground = Color(0xFF9DCCED);
  static const Color quickCommandBarButtonSelectedInnerShadow = Color(0xFFCCEAFF);
}